language: python

services: 
  - docker

env:
  global:
    - GMT_DOCKER_COMPOSE_URL="https://github.com/radon-h2020/radon-gmt/blob/project/radon/docker-compose.yml"
    - GMT_HTTP_PORT="18080"
    - PARTICLES_URL="https://github.com/radon-h2020/radon-particles.git"
    - PARTICLES_BRANCH="master"
    - PARTICLES_DIR="/tmp/radon-particles"
    - EXPORT_URL="http://127.0.0.1:${GMT_HTTP_PORT}/winery/servicetemplates/radon.blueprints/SockShop/?yaml&csar"
    - EXPORT_FILE="${HOME}/export.csar"
    - EXPORT_EXTRACT_FOLDER="${HOME}/export"

before_install:
  - git clone --single-branch --branch "${PARTICLES_BRANCH}" "${PARTICLES_URL}" "${PARTICLES_DIR}"
  - chmod -R a+rwx "${PARTICLES_DIR}"
  - docker-compose up -d

install:
  - pip install -r requirements.txt

script:
  - "curl -H 'Accept: application/xml' -o \"${EXPORT_FILE}\" \"${EXPORT_URL}\""
  - unzip "${EXPORT_FILE}" -d "${EXPORT_EXTRACT_FOLDER}"
  - env ENTRY_DEFINITION=`grep "^Entry-Definitions:" "${EXPORT_EXTRACT_FOLDER}/TOSCA-Metadata/TOSCA.meta" | awk '{print $2}' | cut -d'/' -f2`
  - cd "${EXPORT_EXTRACT_FOLDER}/_definitions"
  - echo "${ENTRY_DEFINITION}"
  - pwd
  - ls -al
  - opera deploy "${ENTRY_DEFINITION}"
  - curl -o /dev/null -s -w "%{http_code}\n" "http://localhost" && exit 0 || exit 1
